### ISSUE TITLE
Add support to light themes

### ISSUE THREAD

**Issue by domferr** [domferr/modernwindowmanager#10]
When using a light theme, the extension's widgets doesn't look right.

**Comment by domferr** [comment]
Fix is ready. Looking to test it before merging into main

**Comment by in4matix** [comment]
I tested it on a VM. Still the same (at least on Ubuntu 22) 
![Screenshot from 2024-04-23 17-44-27](https://github.com/domferr/modernwindowmanager/assets/62904593/4ad139a1-102c-4fce-b7ac-9bb0b7791261)

**Comment by in4matix** [comment]
I'm very happy with the version I'm currently using. Thanks a ton!

**Comment by domferr** [comment]
Closed by version 5 :partying_face:
