### ISSUE TITLE
Rounded buttons

### ISSUE THREAD

**Issue by in4matix** [domferr/modernwindowmanager#14]
Hi, nothing serious, but I prefer the rounded buttons of version 4 above the square buttons of version 5 (for editing and adding layouts), although I must admit the window layout options of version 5 look better than those of version 4.

version 4
![v4](https://github.com/domferr/modernwindowmanager/assets/62904593/dfb71f58-6e30-4120-a233-139cfe49c177)

version 5
![v5](https://github.com/domferr/modernwindowmanager/assets/62904593/80d1916d-b9af-4583-acb2-a24d92d16f0c)

**Comment by domferr** [comment]
> I prefer the rounded buttons of version 4 above the square buttons of version 5 (for editing and adding layouts)

Hehehe, nice spot! I prefer the ones in version 4 too. However, in version 5 that buttons are supposed to be the same buttons of version 4, so there is something going on there.
I think to know were the regression is, I made a fix, can you tell me if it brings back the same buttons of version 4? I attach the archive, and if it solves the problem I update the latest release. Thank you!

- For GNOME Shells from 40 to 44: [GNOME.40-44.modernwindowmanager@ferrarodomenico.com.zip](https://github.com/domferr/modernwindowmanager/files/15210408/GNOME.40-44.modernwindowmanager%40ferrarodomenico.com.zip)
- For GNOME Shells 45 and 46:  [modernwindowmanager@ferrarodomenico.com.zip](https://github.com/domferr/modernwindowmanager/files/15210423/modernwindowmanager%40ferrarodomenico.com.zip)



> although I must admit the window layout options of version 5 look better than those of version 4

Thank you for you feedback!

**Comment by in4matix** [comment]
Yep, fixed now. Thank you!
