### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by in4matix** [domferr/modernwindowmanager#16]
Hey! Just a heads-up on a typo for version 7 - showing as version 6 in Extension Manager:

 
![Screenshot from 2024-05-25 20-21-24](https://github.com/domferr/modernwindowmanager/assets/62904593/e7c8ce9b-c425-4c99-afe0-e7d9621c9213)

**Comment by domferr** [comment]
Ops, thank you! I updated the release with the correct version number.
