### ISSUE TITLE
Mouse Without Borders support?

### ISSUE THREAD

**Issue by alikhan37544** [domferr/modernwindowmanager#17]
Hi, let me describe my use case. 
I have 2 laptops and one desktop. The desktop is usually used to mirror to the weaker laptop and the other laptop runs a project seperately, but related to the main work.
Say for example, if one is web-developing, the desktop screen will have the code for both the website as well as the live implementation, the extra screen connected through spacedesk on the slower laptop will have a live-server localhost view and the third laptop will have the website open completely seperately, not connected to the desktop.
I recently made the switch to Linux on all 3 of my machines (Started on Ubuntu 22 and upgraded to 23 and 24 on all of them, performance and battery life have been miles better )
I used to be able to run spacedesk to easily mirror the screens when that was the use case and also run mouse without borders on all of them so that one good keyboard and mouse could be used to control all of the machines together.
.
Not sure if this is going to be possible, but it's a feature request :)

**Comment by alikhan37544** [comment]
Side note - i clicked on opening an issue on [LinuxPowerToys](https://github.com/domferr/Linux-PowerToys) Readme.md, but it got me here, which I believe is a subset of that. 
Only realised after opening the issue .....

**Comment by domferr** [comment]
Ops...thank you, since both projects are mine, I reused some parts of the README.md and forgot to modify that link!
Can you please open this issue there? (https://github.com/domferr/Linux-PowerToys/issues)
So we can keep the things sorted :smile:

**Comment by alikhan37544** [comment]
Will do, thank you :)
