### ISSUE TITLE
Bring back window's size when it is untiled

### ISSUE THREAD

**Issue by domferr** [domferr/modernwindowmanager#7]
If you untile or move a maximized or tiled window, GNOME brings back the window size as it was before. It would be nice to support the same behaviour, also shown in this video.

[Video del 2024-02-28 22-58-24.webm](https://github.com/domferr/modernwindowmanager/assets/14203981/72b796b3-e5eb-45b0-983d-6646e38b70f4)

**Comment by in4matix** [comment]
Yes please, that is the only flaw I found so far on Ubuntu 22.04. Windows don't restore to their original size.

**Comment by domferr** [comment]
Thank you for your comment! I definitely agree with you. Currently I am working on implementing all the functionalities related to creating and editing layouts. When it's done I will implement the feature described in this issue. I will come back here when I have updates!

**Comment by domferr** [comment]
Hey @in4matix, I just finished working on a major release, introducing the layout editor, and I am now starting to work on this!

(Oh, if you try the new version, after you update you may need to press the "Reset Layouts" button in the preferences).

**Comment by in4matix** [comment]
Hey! The editing of layouts is awesome! This sets MWM in a very competitive position. Everyone can set their own favorite snap zones and have as many as their workflow requires. I am amazed that a program so small can add such a hugely useful functionality to an OS. One downside, I tried the new version on a fresh Ubuntu 22 VM and with default setting, the Yaru shell theme is white and the App seems to be not compatible with white shell themes..
![Screenshot from 2024-04-21 13-53-26](https://github.com/domferr/modernwindowmanager/assets/62904593/42547d38-6910-485c-9e5c-a166dd0707c3)

**Comment by domferr** [comment]
Thank you for your feedback! It means a lot!

Yeah, the extension doesn't support light theme. I made some work to support it, but it's not ready, yet. I am opening a new issue to remember that!

**Comment by domferr** [comment]
> Do I have to rename "[GNOME.40-44.modernwindowmanager@ferrarodomenico.com](mailto:GNOME.40-44.modernwindowmanager@ferrarodomenico.com)" to "[modernwindowmanager@ferrarodomenico.com](mailto:modernwindowmanager@ferrarodomenico.com)" before installing?

Yes, you have to rename "GNOME.40-44.modernwindowmanager@ferrarodomenico.com" to "modernwindowmanager@ferrarodomenico.com" before installing.

> Wow Bro, you have been turbocharging with this! 

I'm planning to publish it! Can't wait to share it to the people. Thank you again for using my extension, you are the very first tester!

**Comment by in4matix** [comment]
Yep, tried without renaming, no go. I am honestly very impressed with this extension (and your coding skills). Windows now resize seamlessly! Well done! Oh, and I didn't have to edit the icon this time round ;-) You should definitely publish it! People are going to love it! Thanks for all your hard work. I am honored to have been the first tester!
