### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by in4matix** [domferr/modernwindowmanager#9]
Is it possible to give the panel icon some attention. It is way to vibrantly white, or, maybe a hot-key setting to launch the editor if the App icon has been set to disabled.
![Screenshot from 2024-04-22 00-11-36](https://github.com/domferr/modernwindowmanager/assets/62904593/09c37397-f73d-4613-88b3-ea97cdcbb978)

**Comment by in4matix** [comment]
Not to worry about this as I have managed to manually edit the icon to match my theme.

**Comment by domferr** [comment]
Uh, nice spot! I'm happy you were able to solve the problem meanwhile.
Would you mind share the name of that theme? I'd like to reproduce the problem to fix the bug in the future. Thank you!

**Comment by in4matix** [comment]
Yes sure, Marble Shell Theme https://github.com/imarkoff/Marble-shell-theme

**Comment by in4matix** [comment]
It is not really a bug at all. I have a very customized Ubuntu 22 setup. Even the Marble Theme has been tweaked to have more transparency and less bright whiteness for icons and text in the menus.

**Comment by in4matix** [comment]
Turns out I ended up editing the Icon again, but purely because I am a painful perfectionist. My top bar is very narrow so this edit was to give the icon a transparent border gap in order for the size of the icon to match the other top icons.

**Comment by domferr** [comment]
> Turns out I ended up editing the Icon again, but purely because I am a painful perfectionist. My top bar is very narrow so this edit was to give the icon a transparent border gap in order for the size of the icon to match the other top icons. [Icon.zip](https://github.com/domferr/modernwindowmanager/files/15081032/Icon.zip)

Uh ok, that's interesting! I will look into other extension and GNOME Shell icons to understand what is the common way to handle this. Thank you!
